Implement Manifest V3 objects and deployment
cloudfoundry/cf-java-client pull request #1167
Opened 2022-09-16 10:09 UTC by schulzh

Implements:
* objects and logic required for reading and writing CC API V3 manifests
* client interface and reactor implementation to apply the manifest
* `pushManifestV3` operation, similar to the existing `pushManifest` operation

I hope that the `pushManifestV3` operation is complete (especially the "app readiness" checks), since I did not find a documentation of this process and had to reverse engineer it from the CLI.

Unfortunately, I could not get a local CF instance set up for the integration tests. Due to licensing issues at my company I cannot use Virtualbox and setting it up on a local OpenStack "DevStack" instance wasn't working either. If requested, I can add integration tests, but I cannot ensure that they are working as intended.

Solves #999 but not #1103 yet

2022-09-16 13:23 UTC, pivotal-david-osullivan commented
Thanks for the PR @schulzh! Are you able to follow the link in the EasyCLA comment above to get the commit authorised 
✅  and satisfy the bot? 

SInce this is a significant addition, if you can add the integration tests I am happy to run them in a lab!

2022-09-21 13:43 UTC, schulzh commented
Hi @pivotal-david-osullivan,

I've added integration tests. Could you please run them in your lab?
I've also completed the CLA. From my side this PR should be ready to merge, so I'd be happy to have it reviewed.

2022-10-05 18:48 UTC, mheath requested changes
This is an amazing contribution. Thank you thank you thank you for all your hard work.

There's a fix that needs to happen in v3/SpacesTest.java (see the comments there)

Other than that, most of the rest of my comments are nitpicks about method order.

Once you fix these things, I'll merge this into its own branch so that I can write acceptance tests for it. Once we have tests, we'll merge this into `main`.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/applications/ApplicationsV3.java
> +    Mono<RestartApplicationResponse> restart(RestartApplicationRequest request);
Even though it makes sense to put "restart" next to "start" and "stop", the convention in CFJC is to keep method names in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/resourcematch/_MatchedResource.java
> +    abstract String getPath();
Put methods in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/spaces/SpacesV3.java
> +    Mono<ApplyManifestResponse> applyManifest(ApplyManifestRequest request);
Put method in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/spaces/_ApplyManifestRequest.java
> +    abstract byte[] manifest();
Rename method to `getManifest()`.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/spaces/_ApplyManifestResponse.java
> +    public abstract Optional<String> jobId();
Rename to `getJobId`.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/spaces/ReactorSpacesV3.java
> +    public Mono<ApplyManifestResponse> applyManifest(ApplyManifestRequest request) {
Keep methods in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/client/v3/AbstractClientV3Operations.java
> +    protected <T> Mono<HttpClientResponseWithParsedBody<T>> postRawWithResponse(byte[] requestPayload, String contentType, Class<T> responseType, Function<UriComponentsBuilder, UriComponentsBuilder>
Methods in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ManifestV3Application.java
> +abstract class _ManifestV3Application extends _ApplicationManifestCommon {
Alphabetize methods names.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ManifestV3Process.java
> +abstract class _ManifestV3Process {
Alphabetize methods names.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ManifestV3Service.java
> +abstract class _ManifestV3Service {
Alphabetize methods names.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ManifestV3Sidecar.java
> +abstract class _ManifestV3Sidecar {
Alphabetize methods.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_Route.java
> +    abstract ManifestV3RouteProtocol getProtocol();
Keep methods in alphabetical order.

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-util/src/main/java/org/cloudfoundry/util/ResourceMatchingUtilsV3.java
> +public final class ResourceMatchingUtilsV3 {
Methods in alphabetical order

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/Applications.java
> +    Mono<Void> pushManifestV3(PushManifestV3Request request);
Add JavaDoc

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java
> +    private static Mono<Void> applyDropletAndWaitForRunning(CloudFoundryClient cloudFoundryClient, String appname, String appId, String dropletId) {
Move private methods to bottom of class and make static (same style as the other privet methods)

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java
> +    private static Flux<DomainResource> requestListDomains(CloudFoundryClient cloudFoundryClient, String organizationId) {
Method in alphabetical order

2022-10-05 18:48 UTC, mheath commented on cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java
> +    private static Mono<Void> waitForV3Running(CloudFoundryClient cloudFoundryClient, String applicationName, String applicationId, Duration startupTimeout) {
Rename to `waitForRunningV3`

2022-10-05 18:48 UTC, mheath commented on integration-test/src/test/java/org/cloudfoundry/client/v3/ResourceMatchTest.java
> +    @IfCloudFoundryVersion(greaterThanOrEqualTo = CloudFoundryVersion.UNSPECIFIED) //TODO how to select this version?
I will look into this

2022-10-05 18:48 UTC, mheath commented on integration-test/src/test/java/org/cloudfoundry/client/v3/SpacesTest.java
> +import sun.misc.IOUtils;
Don't use the `sun.misc` package.

You could use `org.springframework.util.StreamUtils` and change line 279 to something like:
```
byte[] manifest = StreamUtils.copyToByteArray(new ClassPathResource("test-manifest.yml").getInputStream());
```

Or you could do something like:
```
 File file = new ClassPathResource("test-manifest.yml").getFile();
 byte[] manifest = Files.readAllBytes(file.toPath());
```

2022-10-21 20:05 UTC, mheath commented
Will you change the branch from `main` to `manifest-v3` on this PR and I will get it merged and then merge in my acceptance tests?

2022-10-22 00:14 UTC, schulzh commented
Hi @mheath,

I've changed the base branch. It looks like its lagging behind main a few hounded commits. Should I rebase it?

2022-11-01 17:27 UTC, merged

2023-01-17 10:23 UTC, schulzh commented
Hello @mheath,

do you have any updates on this? What is missing to get it merged to master?